- name: Update Penumbra
  hosts: NodesFarm1
  become: true
  gather_facts: no
  tasks:
    - name: Delete Old Update File  
      ansible.builtin.shell: |
        rm -rf update_penumbra.sh
    - name: Clone Updating File
      get_url:
        url: https://raw.githubusercontent.com/DOUBLE-TOP/guides/main/penumbra/update_penumbra.sh
        dest: ~/
    - name: Make Penumbra Update executable 
      ansible.builtin.shell: | 
        chmod +x update_penumbra.sh
    - name: Execute Update
      ansible.builtin.shell: | 
        ./update_penumbra.sh