- name: Update Bundlr
  hosts: NodesFarm1
  become: true
  gather_facts: no
  tasks:
    - name: Delete Old Update File  
      ansible.builtin.shell: |
        rm -rf update_bundler.sh
    - name: Clone Updating File
      get_url:
        url: https://raw.githubusercontent.com/DOUBLE-TOP/guides/main/bundlr/update_bundler.sh
        dest: ~/
    - name: Make Bundlr Update executable 
      ansible.builtin.shell: | 
        chmod +x update_bundler.sh
    - name: Execute Update
      ansible.builtin.shell: | 
        ./update_bundler.sh